apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-$(Build.Repository.Name)
spec:
  selector:
    matchLabels:
      app: $(Build.Repository.Name)
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: $(Build.Repository.Name)
    spec:
      containers:
      - name: $(Build.Repository.Name)
        #image: sip-python
        image: $(ECR_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(Build.Repository.Name):$(Build.BuildNumber)
        ports:
        - containerPort: 80
